version: ‘3’

services:
  cabinvista_nodeapp:
    container_name: cabinvista_nodeapp
    build: .
    ports:
      - 3000:3000

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - “ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnetwork

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnetwork

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnetwork:


#ES PRODUCTION MODE

#The vm.max_map_count kernel setting needs to be set to at least 262144 for production use. Depending on your platform:
#macOS with Docker for Mac
#The vm.max_map_count setting must be set within the xhyve virtual machine:
#$ screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
#Log in with root and no password. Then configure the sysctl setting as you would for Linux:
#sysctl -w vm.max_map_count=262144
